version: '3.8'

services:
  drupal:
    image: drupal:11
    ports:
      - "8080:80"
    volumes:
      - ./modules:/var/www/html/modules
      - files:/var/www/html/sites/default/files
    depends_on:
      - db
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupal_password
      - DRUPAL_DB_NAME=drupal
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    command: /bin/bash -c "composer require drush/drush && chown -R www-data:www-data /var/www/html/sites/default/files && chmod -R 775 /var/www/html/sites/default/files && apache2-foreground"

    restart: always
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: drupal
      PMA_PASSWORD: drupal_password

volumes:
  db_data:
  modules:
  files: